workspace:
  base: /go
  path: src/github.com/uswitch/yggdrasil

pipeline:
  test:
    image: golang:1.17
    environment:
      - GO111MODULE=on
    commands:
      - make test

  build:
    image: golang:1.17
    environment:
      - GO111MODULE=on
    commands:
      - make build-linux

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/yggdrasil
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/yggdrasil
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
