workspace:
  base: /go
  path: src/github.com/uswitch/yggdrasil

pipeline:
  test:
    image: golang:1.10
    commands:
      - go test -v -cover $(go list ./... | grep -v /vendor)

  build:
    image: golang:1.10
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/yggdrasil

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/yggdrasil
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/yggdrasil
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
